@startuml
title 2. Activity Diagram: Approving Loan by Token's Owner
start

if (token's owner approved?) then (yes)
  :read token's calendar;
  if (is token free on selected period?) then (yes)
    :save days in token's calendar;
    :move token into Approved list of loan;
  else (no)
    :move token to declined list of loan;
  endif
else (no)
  :move token to declined list of loan;
endif

:delete request from the owner's list;

end
@enduml