@startuml

title 1. Loan Sequence Diagram

actor Borrower
control BContract
database BStorage
control API
actor Owner

== AddOffer ==

Owner -> BContract: call AddOffer
BContract -> BStorage: check token's type
note right : token has to have saleType = None
BContract -> BStorage: check if exist bids to the token
note right : bids prices have to be lower than the offer price
BContract -> BStorage: call addOffer
BContract -> BContract: emit event OfferAdded
Owner -> Owner: get event OfferAdded
Owner -> BContract: get list of owner's offers

== CancelOffer ==

== BuyOffer ==

== AddBid ==

== AcceptBid ==

== CancelBid ==

|||
@enduml
