@startuml
title Activity Diagram: Distribution Tokens
start

:Distribution of tokens;

:Проверяем возможность снятия блокировки
с токенов, которые долго не забираются пользователем;

if (вызов от пользователя (передан email)?) then (yes)

    if (Есть ли crypto wallet у пользователя?) then (yes)
      :получаем следующие
       N свободных токенов,
       равных количеству купленных;

      :Transfer N tokens;

      :Вычисляем цену в Ether на текущий момент;
      :Записываем в токены цену;
    else (no)

      if (высылали уже DeepLink?) then (yes)
      else (no)
        :Получаем первый свободный токен;
        :Генерируем DeepLink на этот токен;
        :Закрепляем link и hash of 
         link за пользователем;
        :Send DeepLink via email;
      endif

    endif

else (no)
  repeat
    :получаем следующего
    пользователя из списка;

    if (Есть ли crypto wallet у пользователя?) then (yes)
      :получаем следующие
       N свободных токенов,
       равных количеству купленных;

      :Transfer N tokens;

      :Вычисляем цену в Ether на текущий момент;
      :Записываем в токены цену;
    else (no)

      if (высылали уже DeepLink?) then (yes)
      else (no)
        :Получаем первый свободный токен;
        :Генерируем DeepLink на этот токен;
        :Закрепляем link и hash of 
         link за пользователем;
        :Send DeepLink via email;
      endif

    endif

  repeat while (есть еще пользователи в списке?)
endif


end
@enduml