@startuml
title Activity Diagram: Event emits
start

      :получаем следующие
       N свободных токенов,
       равных количеству купленных;

      :Transfer N tokens;

      :Вычисляем цену в Ether на текущий момент;
      :Записываем в токены цену;

end
@enduml