@startuml

title Sequence Diagram: Presale

actor Buyer
participant Frontend
participant BackendAPI
participant Blockchain
participant LinkDrop

autonumber
== Presale by Cryptocurrency ==

Buyer -> Frontend: buy tokens
note right: { number of tokens }
Frontend -> BackendAPI: get list of tokens
note right 
  from shaffled token's list
  and mark them as "bought"
endnote
loop number of tokens
  Frontend -> Blockchain: get offer for tokenId
  Blockchain -> Frontend: { offer id }
  Frontend -> Blockchain: get an offer price
  Blockchain -> Frontend: { offer price }
end
Frontend -> Blockchain: buy offers

autonumber 1 1
== Presale by Linkdrop ==

Buyer -> Frontend: buy tokens
note right: { number of tokens * price in $ }
Frontend -> BackendAPI: buy tokens by credit card
BackendAPI -> BackendAPI: get tokens
note right 
  from shaffled token's list
  and mark them as "bought"
endnote
BackendAPI -> BackendAPI: generate LinkDrop links
BackendAPI -> BackendAPI: send links by email
Buyer -> LinkDrop: open the links
LinkDrop -> BackendAPI: event LogWithdraw
BackendAPI -> BackendAPI: add a wallet number to user accout
BackendAPI -> BackendAPI: calculate a real price 
BackendAPI -> Blockchain: set the last price for token

@enduml